version: '3.4'

services:
  foameropenaiimage:
    image: foameropenaiimage
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 6983:6983
